quality regression: temporary fix for numpy
eventhough previous commit installed numpy, still throwing error.
ImportError: No module named numpy
so before importing trying to install